############################
## Menus directory makefile
############################

DIR := Menus
SUBDIRS :=
LINK_LIBS := sfml-graphics
LIB_DEPS :=
SRCS := \
   MainMenu \
	MainMenuTextButton

include lib.makefile
