####################################################################
## Makefile for tests/util
####################################################################

include cxx/initVars.makefile

DIR := tests/util

FILES := \
   UnitTest

include cxx/sharedLib.makefile
