####################################################################
## Makefile for dsb/generic
####################################################################

include cxx/initVars.makefile

DIR := dsb/generic

FILES := \
   ProjectFile \
   Repository

include cxx/lib.makefile
