####################################################################
## Makefile for tests/BitOps
####################################################################

include cxx/initVars.makefile

DIR := tests/BitOps

FILES := \
   BitOpsUnitTest \
   Int_test \
   Istream_test \
   MultiByteValue \
   NyBitByte_test \
   Optional_test \
   Ostream_test \
   String7_test

include cxx/sharedLib.makefile
