####################################################################
## Makefile for tests/BitOps
####################################################################

include cxx/initVars.makefile

DIR := tests/BitOps

FILES := \
   Int_test

include cxx/lib.makefile
