####################################################################
## Makefile for x2048
####################################################################

include cxx/initVars.makefile

DIR := x2048

SUBDIRS := \
   exe \
   generic

FILES := \
   entryPoint

LINK_STATIC_LIBS := \
   amb-amb \
   amb-x2048-generic \
   amb-Util

LINK_SFML_LIBS := \
   sfml-graphics \
   sfml-window \
   sfml-system

include cxx/sharedLib.makefile
