####################################################################
## Makefile for x2048/generic
####################################################################

include cxx/initVars.makefile

DIR := x2048/generic

FILES := \
   GameBackground \
   x2048App

include cxx/lib.makefile
