####################################################################
## Makefile for tests/infra
####################################################################

include cxx/initVars.makefile

DIR := tests/infra

FILES := \
   UnitTest

LINK_STATIC_LIBS := \
   amb-infra

include cxx/sharedLib.makefile
