###################################
## ProjectEuler directory makefile
###################################

DIR := Minigames/X2048
SUBDIRS :=
LIB_DEPS := Infra
SRCS := \
   X2048Minigame \
   GameBoard \
   Tile \
   TileFactory

include lib.makefile
