####################################################################
## Makefile for dsb/cli/app
####################################################################

include cxx/initVars.makefile

DIR := dsb/cli/app

FILES := \
   Add \
   DsbApp \
   Help \
   Init \
   List \
   Open \
   Rm

include cxx/lib.makefile
