####################################################################
## Makefile for tests/dsb
####################################################################

include cxx/initVars.makefile

DIR := tests/dsb

FILES := \
   UnitTest

LINK_STATIC_LIBS := \
   amb-dsb-gui-app \
   amb-dsb-gui-center \
   amb-dsb-gui-left \
   amb-dsb-gui-top \
   amb-dsb-gui-right \
   amb-dsb-cli-app \
   amb-dsb-generic \
   amb-amb \
   amb-Util

include cxx/sharedLib.makefile
