####################################################################
## Makefile for Util
####################################################################

include cxx/initVars.makefile

DIR := Util

FILES := \
   CommandLine \
   CommandLineOption \
   Log

SYS_LIBS := $(SYS_DLL_LIB)

include cxx/lib.makefile
