####################################################################
## Makefile for Util
####################################################################

include cxx/initVars.makefile

DIR := Util

FILES := \
   ClientSocket \
   CommandLine \
   CommandLineOption \
   Log \
   ServerSocket \
   Socket

SYS_LIBS := $(SYS_DLL_LIB)

include cxx/lib.makefile
