$(info Reading amb/dot/makefile)

include xanrMake/dot/projVars.makefile

all::
	@echo dot all

$(info Inside of dot/makefile)
$(info MAKEFLAGS = $(MAKEFLAGS))
$(info .INCLUDE_DIRS = $(.INCLUDE_DIRS))
$(info )

include dot/vars.makefile
