####################################################################
## Makefile for netbld/master_node
####################################################################

include cxx/initVars.makefile

DIR := netbld/master_node
EXE := master_node

FILES := \
   main \
   Master

include cxx/exe.makefile
