################################
## Minigames directory makefile
################################

#SUBDIRS := MadLib \
#          ProjectEuler \
#          X2048
SUBDIRS := X2048

include $(addprefix $(SRC_DIR)/Minigames/, $(addsuffix /makefile, $(SUBDIRS)))