####################################################################
## Makefile for dsb/gui/left
####################################################################

include cxx/initVars.makefile

DIR := dsb/gui/left

FILES := \
   Button \
   PanelLeft

include cxx/lib.makefile
