####################################################################
## Makefile for dsb/gui/right
####################################################################

include cxx/initVars.makefile

DIR := dsb/gui/right

FILES := \
   ActivityList \
   ListHeader \
   PanelRight \
   ProjectItem

include cxx/lib.makefile
