####################################################################
## Makefile for BuildShell
####################################################################

include cxx/initVars.makefile

DIR := netbld/bldsh
EXE := bldsh

SUBDIRS := \
   generic

FILES := \
   main

LINK_STATIC_LIBS := \
   amb-netbld-bldsh-generic \
   amb-Util

include cxx/exe.makefile
