###################################
## ProjectEuler directory makefile
###################################

DIR := Minigames/ProjectEuler
SUBDIRS := problems
LIB_DEPS := Minigames-ProjectEuler-problems
SRCS := \
   ProjectEulerGame \
   ProblemLoader

include lib.makefile
