####################################################################
## Makefile for netbld
####################################################################

include cxx/initVars.makefile

DIR := netbld

SUBDIRS := \
   bldsh

include cxx/subdirs.makefile
