/*
 * allProblems.h
 *
 *  Created on: Dec 10, 2014
 *      Author: aaron
 */

#ifndef SRC_MINIGAMES_PROJECTEULER_PROBLEMS_ALLPROBLEMS_H_
#define SRC_MINIGAMES_PROJECTEULER_PROBLEMS_ALLPROBLEMS_H_

#include <Minigames/ProjectEuler/problems/UnsolvedProblem.h>
#include <Minigames/ProjectEuler/problems/Problem01.h>
#include <Minigames/ProjectEuler/problems/Problem02.h>
#include <Minigames/ProjectEuler/problems/Problem03.h>
#include <Minigames/ProjectEuler/problems/Problem04.h>
#include <Minigames/ProjectEuler/problems/Problem05.h>
#include <Minigames/ProjectEuler/problems/Problem06.h>
#include <Minigames/ProjectEuler/problems/Problem07.h>
#include <Minigames/ProjectEuler/problems/Problem08.h>
#include <Minigames/ProjectEuler/problems/Problem09.h>
#include <Minigames/ProjectEuler/problems/Problem10.h>
#include <Minigames/ProjectEuler/problems/Problem11.h>
#include <Minigames/ProjectEuler/problems/Problem12.h>
#include <Minigames/ProjectEuler/problems/Problem13.h>
#include <Minigames/ProjectEuler/problems/Problem14.h>
#include <Minigames/ProjectEuler/problems/Problem15.h>
#include <Minigames/ProjectEuler/problems/Problem16.h>
#include <Minigames/ProjectEuler/problems/Problem17.h>
#include <Minigames/ProjectEuler/problems/Problem18.h>
#include <Minigames/ProjectEuler/problems/Problem19.h>
#include <Minigames/ProjectEuler/problems/Problem20.h>
#include <Minigames/ProjectEuler/problems/Problem21.h>
#include <Minigames/ProjectEuler/problems/Problem22.h>
#include <Minigames/ProjectEuler/problems/Problem23.h>
#include <Minigames/ProjectEuler/problems/Problem24.h>
#include <Minigames/ProjectEuler/problems/Problem25.h>
#include <Minigames/ProjectEuler/problems/Problem26.h>
#include <Minigames/ProjectEuler/problems/Problem27.h>
#include <Minigames/ProjectEuler/problems/Problem28.h>
#include <Minigames/ProjectEuler/problems/Problem29.h>
#include <Minigames/ProjectEuler/problems/Problem30.h>
#include <Minigames/ProjectEuler/problems/Problem31.h>
#include <Minigames/ProjectEuler/problems/Problem32.h>
#include <Minigames/ProjectEuler/problems/Problem33.h>
#include <Minigames/ProjectEuler/problems/Problem34.h>
#include <Minigames/ProjectEuler/problems/Problem35.h>
#include <Minigames/ProjectEuler/problems/Problem36.h>
#include <Minigames/ProjectEuler/problems/Problem37.h>
#include <Minigames/ProjectEuler/problems/Problem38.h>
#include <Minigames/ProjectEuler/problems/Problem39.h>
#include <Minigames/ProjectEuler/problems/Problem40.h>
#include <Minigames/ProjectEuler/problems/Problem41.h>
#include <Minigames/ProjectEuler/problems/Problem42.h>
#include <Minigames/ProjectEuler/problems/Problem43.h>
#include <Minigames/ProjectEuler/problems/Problem44.h>
#include <Minigames/ProjectEuler/problems/Problem45.h>
#include <Minigames/ProjectEuler/problems/Problem46.h>
#include <Minigames/ProjectEuler/problems/Problem47.h>
#include <Minigames/ProjectEuler/problems/Problem48.h>
#include <Minigames/ProjectEuler/problems/Problem49.h>
#include <Minigames/ProjectEuler/problems/Problem50.h>
#include <Minigames/ProjectEuler/problems/Problem51.h>
#include <Minigames/ProjectEuler/problems/Problem52.h>
#include <Minigames/ProjectEuler/problems/Problem53.h>
#include <Minigames/ProjectEuler/problems/Problem54.h>
#include <Minigames/ProjectEuler/problems/Problem55.h>
#include <Minigames/ProjectEuler/problems/Problem56.h>
#include <Minigames/ProjectEuler/problems/Problem57.h>
#include <Minigames/ProjectEuler/problems/Problem58.h>
#include <Minigames/ProjectEuler/problems/Problem59.h>
#include <Minigames/ProjectEuler/problems/Problem60.h>
#include <Minigames/ProjectEuler/problems/Problem61.h>
#include <Minigames/ProjectEuler/problems/Problem62.h>
#include <Minigames/ProjectEuler/problems/Problem63.h>
#include <Minigames/ProjectEuler/problems/Problem64.h>
#include <Minigames/ProjectEuler/problems/Problem65.h>
#include <Minigames/ProjectEuler/problems/Problem66.h>
#include <Minigames/ProjectEuler/problems/Problem67.h>
#include <Minigames/ProjectEuler/problems/Problem68.h>
#include <Minigames/ProjectEuler/problems/Problem69.h>
#include <Minigames/ProjectEuler/problems/Problem70.h>
#include <Minigames/ProjectEuler/problems/Problem71.h>
#include <Minigames/ProjectEuler/problems/Problem72.h>
#include <Minigames/ProjectEuler/problems/Problem73.h>
#include <Minigames/ProjectEuler/problems/Problem74.h>
#include <Minigames/ProjectEuler/problems/Problem75.h>
#include <Minigames/ProjectEuler/problems/Problem76.h>
#include <Minigames/ProjectEuler/problems/Problem77.h>
#include <Minigames/ProjectEuler/problems/Problem78.h>
#include <Minigames/ProjectEuler/problems/Problem79.h>
#include <Minigames/ProjectEuler/problems/Problem80.h>
#include <Minigames/ProjectEuler/problems/Problem81.h>
#include <Minigames/ProjectEuler/problems/Problem82.h>
#include <Minigames/ProjectEuler/problems/Problem83.h>
#include <Minigames/ProjectEuler/problems/Problem84.h>
#include <Minigames/ProjectEuler/problems/Problem85.h>
#include <Minigames/ProjectEuler/problems/Problem86.h>
#include <Minigames/ProjectEuler/problems/Problem87.h>
#include <Minigames/ProjectEuler/problems/Problem88.h>
#include <Minigames/ProjectEuler/problems/Problem89.h>
#include <Minigames/ProjectEuler/problems/Problem90.h>
#include <Minigames/ProjectEuler/problems/Problem91.h>
#include <Minigames/ProjectEuler/problems/Problem92.h>
#include <Minigames/ProjectEuler/problems/Problem93.h>
#include <Minigames/ProjectEuler/problems/Problem94.h>
#include <Minigames/ProjectEuler/problems/Problem95.h>
#include <Minigames/ProjectEuler/problems/Problem96.h>
#include <Minigames/ProjectEuler/problems/Problem97.h>
#include <Minigames/ProjectEuler/problems/Problem98.h>
#include <Minigames/ProjectEuler/problems/Problem99.h>

#endif /* SRC_MINIGAMES_PROJECTEULER_PROBLEMS_ALLPROBLEMS_H_ */
