############################################
## ProjectEuler problems directory makefile
############################################

DIR := Minigames/ProjectEuler/problems
SUBDIRS :=
LIB_DEPS :=
SRCS := \
   Problem01 \
   Problem02 \
   UnsolvedProblem

include lib.makefile
