/*
 * Problem02.cpp
 *
 */

#include <string>
#include <Minigames/ProjectEuler/problems/Problem02.h>

namespace Minigames {
namespace ProjectEuler {

Problem02::Problem02()
{
   // Empty
}

Problem02::~Problem02()
{
   // Empty
}

std::string Problem02::getText()
{
   return "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n"
                "\t\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n"
                 "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms";
}

std::string Problem02::getSolution()
{
   long long fib1 = 1;
   long long fib2 = 2;
   long long fibSum = fib1 + fib2;
   long long total = 0;

   if (fib1 % 2 == 0)
   {
      total += fib1;
   }
   if (fib2 % 2 == 0)
   {
      total += fib2;
   }

   while (fibSum < 4000000)
   {
      if (fibSum % 2 == 0)
      {
         total += fibSum;
      }

      fib1 = fib2;
      fib2 = fibSum;
      fibSum = fib1 + fib2;
   }

   std::stringstream ss;
   ss << "The total sum is: " << total << std::endl;

   return ss.str();
}

} /* namespace ProjectEuler */
} /* namespace Minigames */
