####################################################################
## Makefile for infra
####################################################################

include cxx/initVars.makefile

DIR := infra

FILES := \
   MsgSys

include cxx/lib.makefile
