####################################################################
## Makefile for tests/amb
####################################################################

include cxx/initVars.makefile

DIR := tests/amb

FILES := \
   UnitTest

LINK_STATIC_LIBS := \
   amb-amb \
   amb-amb-xml

include cxx/sharedLib.makefile
