####################################################################
## Makefile for amb/xml
####################################################################

include cxx/initVars.makefile

DIR := amb/xml

FILES := \
   Node

include cxx/lib.makefile
