####################################################################
## Makefile for bldsh/generic
####################################################################

include cxx/initVars.makefile

DIR := netbld/bldsh/generic

FILES := \
   BuildCmdMessage \
   CmdLineParser

include cxx/lib.makefile
