####################################################################
## Makefile for BuildShell
####################################################################

$(info Reading amb/cxx/BuildShell/makefile)
$(info )

include cxx/initVars.makefile

DIR := BuildShell
EXE := BuildShell

FILES := \
   BuildShell

include cxx/exe.makefile
