####################################################################
## Makefile for bldsh/generic
####################################################################

include cxx/initVars.makefile

DIR := bldsh/generic

FILES := \
   BuildCmdMessage

include cxx/lib.makefile
