####################################################################
## Makefile for paint
####################################################################

include cxx/initVars.makefile

DIR := paint

FILES := \
   entryPoint

SUBDIRS := \
   exe \
   generic

LINK_STATIC_LIBS := \
   amb-amb \
   amb-paint-generic \
   amb-Util

LINK_SFML_LIBS := \
   sfml-graphics \
   sfml-window \
   sfml-system

include cxx/sharedLib.makefile
