####################################################################
## Makefile for paint/lib
####################################################################

include cxx/initVars.makefile

DIR := paint/generic

FILES := \
   BrushStroke \
   PaintApp \
   SmallBrush

include cxx/lib.makefile
