####################################################################
## Makefile for NetworkBuild
####################################################################
$(info Reading amb/python/NetworkBuild/makefile)

include python/initVars.makefile

DIR := NetworkBuild

SUBDIRS := \
   concurrencylive

FILES := \
   BuildNodeManager \
   BuildShell \
   MasterNodeManager

include python/exe.makefile
