###########################
# Main directory makefile #
###########################
DIRECTORY = Main
SUBDIRS = 
SRCS = Main

# Be sure to add the same exe name you listed here
EXE = AmbGames
LIB_DEPENDENCIES = \
                   Infra \
                   Menus \
                   Minigames-MadLib \
                   Minigames-X2048 \
                   Minigames-ProjectEuler \
                   Minigames-ProjectEuler-problems

include module.makefile
