###########################
## Main directory makefile
###########################

DIR := Main
SUBDIRS :=
SRCS := Main
EXE := AmbGames
LINK_LIBS :=
LIB_DEPS := \
           Infra \
           Menus \
           Minigames-X2048
#           Minigames-MadLib \
#           Minigames-ProjectEuler \
#           Minigames-ProjectEuler-problems

include module.makefile
