# prog directory makefile

AMB_BUILD_SUBDIRS += Main

DIRECTORY = Main
SUBDIRS = 
SRCS = Main

# Be sure to add the same exe name you listed here, to the  
EXE = AmbGames
LINK_LIBS += Minigames-MadLib Minigames-DumbGame Minigames-ProjectEuler Minigames-ProjectEuler-problems

include module.makefile
