####################################################################
## Makefile for dsb/cli
####################################################################

include cxx/initVars.makefile

DIR := dsb/cli

SUBDIRS := \
   app

FILES := \
   entry_points

LINK_STATIC_LIBS := \
   amb-dsb-cli-app \
   amb-dsb-generic

include cxx/sharedLib.makefile
