####################################################################
## Makefile for tests/std
####################################################################

include cxx/initVars.makefile

DIR := tests/std

FILES := \
   typeinfo_test \
   UnitTest

include cxx/sharedLib.makefile
