####################################################################
## Makefile for dsb/gui/top
####################################################################

include cxx/initVars.makefile

DIR := dsb/gui/top

FILES := \
   Button \
   PanelTop \
   SearchBar

include cxx/lib.makefile
