####################################################################
## Makefile for dsb
####################################################################

include cxx/initVars.makefile

DIR := include

# This causes the xml files to show up in the Project Explorer in VS
ifeq "$(MAKE_TYPE)" "Windows"
   include cxx/lib.makefile
endif
