#############################
## MadLib directory makefile
#############################

DIR = Minigames/MadLib
SUBDIRS =
LIB_DEPS =
SRCS = \
   Library \
   Helper \
   MadLibMinigame

include lib.makefile

