####################################################################
## Makefile for tests/paint
####################################################################

include cxx/initVars.makefile

DIR := tests/paint

FILES := \
   UnitTest

LINK_STATIC_LIBS := \
   amb-paint-generic

include cxx/sharedLib.makefile
