$(info Reading amb/python/makefile)

include xanrMake/python/projVars.makefile

all::
	@echo python all

$(info Inside of python/makefile)
$(info MAKEFLAGS = $(MAKEFLAGS))
$(info .INCLUDE_DIRS = $(.INCLUDE_DIRS))
$(info )

include python/vars.makefile
