#!/bin/zsh -ef

## Configuration
mfile=makefile

## Functions
function echof () {
  echo $* >> $mfile
}

function makeBackup () {
  if [[ -e "$mfile" ]]; then
    cp --force --backup=numbered $* $*
    rm $*
  fi
}

## Parse command line
if (($#argv >= 1)); then
   if [[ "$1" == "--exe" ]]; then
      makeType="exe"
   elif [[ "$1" == "--lib" ]]; then
      makeType="lib"
   elif [[ "$1" == "--sharedLib" ]]; then
      makeType="sharedLib"
   elif [[ "$1" == "--subdir" ]]; then
      makeType="subdirs"
   else
      echo "Invalid argument:" >&2
      echo "You should specify makefile type [--exe, --lib, --sharedLib]" >&2
      exit 1
   fi
else
   echo "You should specify makefile type [--exe, --lib, --sharedLib]" >&2
   exit 1
fi

makeBackup $mfile

amb_lang=""
amb_languages=(cxx dot python)
subdirs=(${(ws:/:)PWD})
for subdir in $subdirs; do
   for lang in $amb_languages; do
      if [[ "$subdir" == "$lang" ]]; then
         amb_lang="$lang"
         break
      fi
   done
done

if [[ "$amb_lang" == "" ]]; then
   echo "Where are you??" >&2
   exit 1
fi

lang_index=${subdirs[(i)$amb_lang]}
directory=${(j:/:)subdirs[$lang_index+1,-1]}

items=(`ls --hide="*.cpp" --hide="*.h"`)
fileList=`ls *.cpp`
subdirList=()
for i in $items; do
   if [[ -d "$i" ]]; then
      subdirList+="$i"
   fi
done

files=(`echo "${fileList}" | sort`)
subdirs=(`echo $subdirList | sort`)

echof "####################################################################"
echof "## Makefile for $directory"
echof "####################################################################"
echof ""
echof "include $amb_lang/initVars.makefile"
echof ""
echof "DIR := $directory"

if [[ "$makeType" == "exe" ]]; then
   echof "EXE := $directory:t"
fi

if (( $#subdirs )); then
   echof ""
   echof -n "SUBDIRS :="
   for d in $subdirs; do
      echof -en " \\"
      echof -en "\n   $d"
   done
   echof ""
fi

if (( $#files )); then
   echof ""
   echof -n "FILES :="
   for f in $files; do
      echof -en " \\"
      echof -en "\n   $f:r"
   done
   echof ""
fi

echof ""
echof "include $amb_lang/$makeType.makefile"
