####################################################################
## Makefile for NetworkBuild/concurrencylive
####################################################################

include python/initVars.makefile

DIR := NetworkBuild/concurrencylive

FILES := \
   aserver \
   perf1 \
   perf2 \
   perf3 \
   server

include python/exe.makefile
