####################################################################
## Makefile for dsb/gui/app
####################################################################

include cxx/initVars.makefile

DIR := dsb/gui/app

FILES := \
   DsbApp

include cxx/lib.makefile
