####################################################################
## Makefile for x2048/exe
####################################################################

include cxx/initVars.makefile

DIR := x2048/exe
EXE := x2048

FILES := \
   main

LINK_STATIC_LIBS := \
   amb-Util

LINK_DYNAMIC_LIBS := \
   amb-x2048

include cxx/exe.makefile
