##############################
# The src directory makefile #
##############################

SUBDIRS = \
   Infra \
   Main \
   Menus \
   Minigames

include $(addprefix $(AMB_SRC_DIR)/, $(addsuffix /makefile, $(SUBDIRS)))

