##############################
# The src directory makefile #
##############################

SUBDIRS := \
   Infra \
   Main \
   Menus \
   Minigames

include $(addprefix $(SRC_DIR)/, $(addsuffix /makefile, $(SUBDIRS)))

