####################################################################
## Makefile for BitOps
####################################################################

include cxx/initVars.makefile

DIR := BitOps

FILES :=

#include cxx/sharedLib.makefile
