####################################################################
## makefile for amb
####################################################################

include dot/initVars.makefile

DIR := NetworkBuild

FILES := \
   Graph

include dot/png.makefile
