####################################################################
## Makefile for dsb/gui/center
####################################################################

include cxx/initVars.makefile

DIR := dsb/gui/center

FILES := \
   Activity \
   Category \
   PanelCenter

include cxx/lib.makefile
